config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tags' => 'tags#index'
  get '/tags/:id' => 'tags#show', as: :tag
  get '/destinations/:id' => 'destinations#show', as: :destination
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/destination.rb
class Destination < ApplicationRecord
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    def show
        @destination = Destination.find(params[:id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end

    def show
        @tag = Tag.find(params[:id])
        @destinations = @tag.destinations
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desctination_helper.rb
module DesctinationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/destinations/show.html.erb
<div class="header">
  <div class="container">
    <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= image_tag @destination.image %>
        <h2><%= @destination.name %></h2>
        <p><%= @destination.description %></p>
      
      </div>
    </div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<div class="header">
  <div class="container">
    <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    
    <% @tags.each do |tag| %>
        <div class="card col-xs-4">
          <%=image_tag tag.image %>
          <h2><%= tag.title %></h2>
          <%= link_to "Learn more", tag_path(tag) %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/tags/show.html.erb
<div class="header">
  <div class="container">
    <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tag">
  <div class="container">
    <h2 class="tag-title"><%= @tag.title %></h2>

    <div class="cards row">

     <% @destinations.each do |d| %>
      <div class="card col-xs-4">
        <%= image_tag d.image %>
        <h2><%= d.name %></h2>
        <p><%= d.description %></p>
        <%= link_to "See more", destination_path(d) %>
      </div>
    <% end %>

    </div>

  </div>
</div>